name: Whitesource Prioritize

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Maven Install
      run: mvn clean install -DskipTests=true
    - name: WhiteSource Scan
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
      run: |
        cat <<EOF > eua.config
        apiKey=$WS_APIKEY
        userKey=$WS_USERKEY
        productName="GH_${{ github.event.repository.name }}"
        projectName="${{ github.ref }} (EUA)""
        enableImpactAnalysis=true
        requireKnownSha1=false
        resolveAllDependencies=false
        maven.resolveDependencies=true
        maven.aggregateModules=true
        fileSystemScan=false
        generateProjectDetailsJson=true
        includes=**/*.jar
        EOF
        cat eua.config
        echo config created successfully
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        curl -o xModuleAnalyzer.jar https://unified-agent.s3.amazonaws.com/xModuleAnalyzer/xModuleAnalyzer-21.4.1.jar
        echo WhiteSource Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar -d ./ -analyzeMultiModule multimodule.txt
        echo 'multimodule.txt contents'
        cat multimodule.txt
        java -jar xModuleAnalyzer.jar -xModulePath multimodule.txt -fsaJarPath ./wss-unified-agent.jar -c ./eua.config -aggregateModules true
